Various bugs and error handling

diff --git a/bin/vol b/bin/vol
--- a/bin/vol
+++ b/bin/vol
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 MIX=amixer
+CARD=0
+NUMID=1
+
 declare -i LO=0     # Minimum volume; try 10 to avoid complete silence
 declare -i HI=100   # Maximum volume; try 95 to avoid distortion
 declare -i ADJ=3    # Volume adjustment step size
@@ -36,13 +39,13 @@ if [ -z "$EXE" ]; then
 	exit 2
 fi
 
-GET=$(${EXE} cget numid=1)
-declare -i MIN=$(echo ${GET} | /bin/grep -E -o -e ',min=[^,]+' | /bin/grep -E -o -e '[0-9-]+')
-declare -i MAX=$(echo ${GET} | /bin/grep -E -o -e ',max=[^,]+' | /bin/grep -E -o -e '[0-9-]+')
-declare -i VAL=$(echo ${GET} | /bin/grep -E -o -e ': values=[0-9+-]+' | /bin/grep -E -o -e '[0-9-]+')
+GET="$EXE cget -c $CARD numid=$NUMID"
+MIN=`$GET | /bin/grep -v dB | /bin/grep -E -o -e ',min=[^,]+' | /bin/grep -E -o -e '[0-9-]+'`
+MAX=`$GET | /bin/grep -v dB | /bin/grep -E -o -e ',max=[^,]+' | /bin/grep -E -o -e '[0-9-]+'`
+VAL=`$GET | /bin/grep -E -o -e ': values=[0-9+-]+' | /bin/grep -E -o -e '[0-9-]+'`
 
 if (( MIN >= MAX || VAL < MIN || VAL > MAX )); then
-	echo "Error: could not get the right values from $MIX output." >&2
+	echo "Error: could not get the right values from $MIX output. $MIN $MAX $VAL" >&2
 	exit 3
 fi
 
@@ -70,7 +73,7 @@ if [ ! -z "$ARG" ]; then
 	if [[ "$PCT" != "$OLD" ]]; then
 		(( ABS = PCT * LEN / 100 ))
 		(( VAL = MIN + ABS ))
-		${EXE} -q cset numid=1 -- ${VAL}
+		${EXE} -c ${CARD} -q cset numid=${NUMID} -- ${VAL}
 	fi
 fi
 
